version: '3'

services:
  web:
    image: 394072917019.dkr.ecr.ap-northeast-1.amazonaws.com/nginx-ecr:latest
    build: 
      dockerfile: ./infra/web/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./api:/var/www
    tty: true
    stdin_open: true